easy_admin:
    entities:
        User: 
            label: 'Users'
            class: AppBundle\Entity\User
            list:
                title: "User list"
                fields: ['id', 'username', 'email', 'lastLogin', 'enabled', 'locked']
                actions: ['-show']
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }
                    - { property: 'enabled', type: 'checkbox' }
                    - { property: 'locked', type: 'checkbox' }
        Customer:
            class: AppBundle\Entity\Customer
            list:
                fields: 
                    - user
                    - name
                    - { property: 'logo', type: 'image', base_path: 'http://localhost/sfEasyAdmin/web/images/customers/' }
                    - email
                    - createdAt
            show:
                fields:
                    - user
                    - name
                    - { property: 'logo', type: 'image', base_path: 'http://localhost/sfEasyAdmin/web/images/customers/' }
                    - firstName
                    - lastname
                    - email
                    - phone
                    - companyName
                    - website
            form:
                fields:
                    - user
                    - name
                    - { property: 'logoFile', type: 'file', label: 'Upload logo', help: 'Select file to upload / change logo' }
                    - firstName
                    - lastname
                    - { property: 'email', type: 'email' }
                    - phone
                    - companyName
                    - website