easy_admin:
    entities:
        User: 
            label: 'Users'
            class: AppBundle\Entity\User
            list:
                title: "User list"
                fields: ['id', 'username', 'email', 'lastLogin', 'enabled', 'locked']
                actions: ['-show']
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }
                    - { property: 'enabled', type: 'checkbox' }
                    - { property: 'locked', type: 'checkbox' }
        Customer:
            class: AppBundle\Entity\Customer
            form:
                fields: ['user', 'name', 'firstName', 'lastName', 'email', 'phone', 'companyName', 'website']